(require 'auto-complete)
(require 'go-autocomplete)
(require 'auto-complete-config)
(ac-config-default)
(require 'go-eldoc)
(add-hook 'go-mode-hook 'go-eldoc-setup)
(add-hook 'before-save-hook #'(lambda ()
				(gofmt-before-save)
				(auto-complete-mode))
(global-auto-complete-mode -1))
(provide 'config-go)
