(require 'go-complete)
(add-hook 'completion-at-point-functions 'go-complete-at-point)
(add-hook 'before-save-hook #'(lambda ()
				(gofmt-before-save)
				(set (make-local-variable 'compile-command) "go build")))
(provide 'config-go)
