(require 'em-tramp)
(eval-after-load 'eshell '(setenv "CC" "gcc"))
(eshell-command "alias sudo 'eshell/sudo $*'")
(exec-path-from-shell-initialize)
(add-hook 'eshell-mode-hook #'(lambda () (nlinum-mode -1) (setq eshell-path-env (getenv "PATH"))))
(if (not (eq system-type 'windows-nt))
    (exec-path-from-shell-initialize)
  (setq exec-path (split-string eshell-path-env ":")))
(provide 'config-eshell)
