plugins: chroma embedart fetchart lyrics acousticbrainz lastgenre
directory: ~/Music
library: ~/Music/library.db
import:
  copy: yes
acoustid:
    apikey: key
fetchart:
  auto: yes
lyrics:
  auto: yes
