#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
#daemons
# screen powersave
xset +dpms
xset dpms 0 0 300
#dunst -config .dunstrc &
/usr/lib/notification-daemon-1.0/notification-daemon &
xmodmap .Xmodmap
#emacs --daemon &
#/usr/lib64/gnome-settings-daemon/gnome-settings-daemon &
xsetroot -cursor_name left_ptr
#exec dbus-launch --exit-with-session emacs
exec i3
#exec gnome-session

#export XDG_CURRENT_DESKTOP=GNOME-Classic:GNOME
#export GNOME_SHELL_SESSION_MODE=classic
#exec gnome-session --session=gnome-classic

# exec startkde
# exec startxfce4
# exec gnome-session
# ...or the Window Manager of your choice
