#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
#daemons
# screen powersave
xset +dpms
xset dpms 0 0 300
dunst -config .dunstrc &
xmodmap .Xmodmap
dbus-daemon
emacs --daemon 
xinput set-prop 8 272 -1
#/usr/lib64/gnome-settings-daemon/gnome-settings-daemon &
xsetroot -cursor_name left_ptr
#exec dbus-launch --exit-with-session emacs
exec i3
# exec startkde
# exec startxfce4
# exec gnome-session
# ...or the Window Manager of your choice
