#!/bin/sh
#stuff executed on startup
dunst -config .dunstrc &
redshift -l 30:78 &
xmodmap .Xmodmap
xrdb -merge ~/.Xresources
emacs --daemon &
feh --bg-scale /usr/share/backgrounds/gnome/Dark_Ivy.jpg 
