;; add package repos
(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.milkbox.net/packages/"))
(package-initialize)
(defun install-package (package)
  (unless (package-installed-p package)
    (package-install package)))
;; install packages
(install-package 'auctex)
(install-package 'auto-compile)
(install-package 'magit)
(install-package 'ir-black-theme)
(install-package 'paredit)
(install-package 'xkcd)
(install-package 'smart-mode-line)
(install-package 'latex-pretty-symbols)
(install-package 'undo-tree)
(install-package 'ido-ubiquitous)
(install-package 'ido-at-point)
(install-package 'smex)
(install-package 'nlinum)
(install-package 'gist)
(install-package 'iedit)
(install-package 'multiple-cursors)
(install-package 'clues-theme)
(install-package 'ix)
(install-package 'dired-details+)
(install-package 'emms)
(install-package 'god-mode)
(install-package 'flx-ido)
(install-package 'scheme-complete)
(install-package 'all)
(install-package 'google-translate)
(install-package 'google-c-style)
;; install el-get
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")
(setq el-get-github-default-url-type "http")
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "http://raw.github.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(setq el-get-user-package-directory "~/.emacs.d/elisp/config/")
(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)
(provide 'config-packages)
