(package-initialize)
(add-to-list 'load-path "~/.emacs.d/elisp/")

(require 'config-packages)
(require 'config-addons)
(require 'config-c)
(require 'config-functions)
(require 'config-gui)
(require 'config-keybind)
(require 'config-latex)
(require 'config-lisp)
(require 'config-skeleton)
(require 'config-variables)
(require 'config-ido)
(require 'config-eshell)
(require 'config-dired)
(require 'config-ispell)
